# Generated by Django 4.2.6 on 2023-11-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Img',
            field=models.ImageField(default='jnjkvndv', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
